application: kcahealth-1101
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index.html

- url: /assets
  static_dir: assets

- url: /images
  static_dir: images

- url: /calendar.html
  static_files: calendar.html
  upload: calendar.html

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /expert.html
  static_files: expert.html
  upload: expert.html

- url: /ourStory.html
  static_files: ourStory.html
  upload: ourStory.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
